support parsing multiple packages per line
Leonidas-from-XIV/nosetup pull request #2
Opened 2017-10-11 13:44 UTC by vogler

.merlin allows multiple packages per line, so
~~~
PKG foo bar
~~~
instead of
~~~
PKG foo
PKG bar
~~~
should also be supported.

2017-10-11 13:57 UTC, Leonidas-from-XIV requested changes
Thanks, that's a very useful addition. I found some useless code, after that I'm ok with merging it.

2017-10-11 13:57 UTC, Leonidas-from-XIV commented on src/merlin_parser.ml
> +  print_endline "hallo";
Line left over.

2017-10-11 14:01 UTC, vogler commented on src/merlin_parser.ml
> +  print_endline "hallo";
Ups, sorry 😄

2017-10-12 07:31 UTC, Leonidas-from-XIV approved these changes

2017-10-12 07:31 UTC, merged

2017-10-12 07:32 UTC, Leonidas-from-XIV commented
Thanks! I'll release it after the angstrom 0.7 release hits OPAM.